name: crablst1
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python=3.8
  - astropy~=4.2
  - pip
  - pre-commit
  - ctapipe~=0.12
  - ruamel.yaml>=0.17
  - protobuf=3.20
  - jupyterlab
  - pip:
      - lstchain==0.9.9
      - lstmcpipe==0.9.0
