name: crablst1
channels:
  - cta-observatory
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - astropy=4.3.1
  - pip=23.0.1
  - pre-commit=3.2.0
  - ctapipe=0.12.0
  - ruamel.yaml=0.17.21
  - libprotobuf=3.20.2
  - protobuf=3.20.2
  - jupyterlab=3.6.2
  - pip:
    - click==8.1.3
    - ctapipe-io-lst==0.18.2
    - ctaplot==0.6.2
    - deepdiff==6.3.0
    - dnspython==2.3.0
    - exceptiongroup==1.1.1
    - gammapy==0.19
    - iniconfig==2.0.0
    - ipympl==0.9.3
    - jinja2==3.0.3
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - lstchain==0.9.9
    - lstmcpipe==0.9.0
    - numpy==1.21.6
    - ordered-set==4.1.0
    - pandas==1.5.3
    - pluggy==1.0.0
    - protozfits==2.1.0
    - pydantic==1.10.6
    - pyirf==0.6.0
    - pymongo==4.3.3
    - pytest==7.2.2
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - regions==0.5
    - seaborn==0.12.2
    - toml==0.10.2
