name: crablst1
channels:
  - cta-observatory
  - conda-forge
  - default
dependencies:
  - python=3.8.16
  - numpy=1.21
  - astropy=4.3.1
  - pip=23.0.1
  - ctapipe=0.12.0
  - gammapy=0.19
  - h5py=3.8.0
  - ipython=8.12.0
  - jupyterlab=3.6.3
  - matplotlib=3.5
  - iminuit=2.21.3
  - joblib=1.2.0
  - toml=0.10.2
  - protozfits=2.0
  - protobuf=3.20
  - pyparsing=3.0.9
  - scikit-learn=1.0.2
  - sphinx=4.5.0
  - sphinx-automodapi=0.15.0
  - sphinx_rtd_theme=1.2.0
  - sphinx-argparse=0.4.0
  - nbsphinx=0.9.1
  - numba=0.56.4
  - numpydoc=1.5.0
  - pandas=2.0.0
  - pymongo=4.3.3
  - seaborn=0.12.2
  - jinja2=3.0 
  - pip:
      - ctapipe_io_lst==0.18.2
      - ctaplot==0.6.2
      - pyirf==0.6.0
      - lstmcpipe==0.9.0
      - lstchain==0.9.9