name: crablst1
channels:
  - cta-observatory
  - conda-forge
  - default
dependencies:
  - python=3.8.16
  - numpy=1.21.6
  - astropy=4.3.1
  - pip=23.1.1
  - gammapy=0.19
  - jupyterlab=3.0.7
  - matplotlib=3.5.3
  - joblib=1.2.0
  - scikit-learn=1.0.2
  - pandas=2.0.1
  - seaborn=0.12.2
  - pip:
      - ctaplot==0.6.2
      - pyirf==0.6.0
