name: Run Jupyter Notebooks

on:
  push:
    branches:
      - mindeps
  pull_request:
    branches:
      - main

jobs:
  run-notebooks:
    name: Run notebooks
    runs-on: "ubuntu-22.04.2"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: crablst1
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          chmod +x run_all_notebooks.sh
          ./run_all_notebooks.sh .
          